### ISSUE TITLE
[W7-Kaggle_competition] Alfredo Zavala

### ISSUE THREAD

**Issue by alfredozavala14** [Ironhack-Data-Madrid-Enero-2021/W7-Kaggle_competition#15]
https://github.com/alfredozavala14/diamond-competition-kaggle

**Comment by breogann** [comment]
Hola Alfredo! 🙋🏻‍♂️

En **general** (esto es un resumen del planteamiento de machine learning, así que puedes obviarlo y bajar un poco más), los objetivos y estrategias del proyecto:

Hay que elegir el modelo que mejor te prediga en base a unos datos. Para elegir el mejor modelo de machine learning, hay cuatro variables que podemos controlar:

- Procesamiento de los datos
- Cómo separamos los datos para hacer el train/test.
- Qué modelo utilizamos.
- Qué parámetros utilizamos en ese modelo.

Para cada uno de ellos hay una estrategia:

1. **Encoders & Standarization**: para las variables categóricas: [aquí](https://medium.com/@michaeldelsole/what-is-one-hot-encoding-and-how-to-do-it-f0ae272f1179) (también hay otras estrategias, como é[sta](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html), o incluso hacer un diccionario donde a cada letra le asignes un valor numérico relativo al resto. Claro que esto te puede valer cuando tienes pocos datos.
2. ***Cross-validation:** para garantizar el corte de los datos: [aquí](https://medium.com/analytics-vidhya/introduction-to-cross-validation-k-fold-7ed9cbd0ed7b)
3. **Modelo de regresión**: probar varios, [aquí](https://medium.com/technology-nineleaps/popular-machine-learning-algorithms-a574e3835ebb)
4. **Grid search**: para las permutaciones de los parámetros: [aquí](https://medium.com/fintechexplained/what-is-grid-search-c01fe886ef0a)

**o grid search con cross-validation, como has hecho*

########################################################################

En **particular**: 

- Respecto a la **organización del repositorio y el readme:** está perfecto. Lo único que te puedo decir es que en las carpetas de output pongas datos que hayas procesado; que sean resultado de la manipulación de datos. Las imágenes las puedes meter en un carpeta de imgs.
- Genial por modularizar y hacer el docstring. No hacía falta para este proyecto, pero es súper útil para pre-procesar la submission.
- El **código 👩‍💻:**
    - Como bonus personal, ¿para qué sirve cada parámetro?, ¿por qué utilizando un valor u otro mejora o no el resultado?
    - Por último, puedes explorar H20:  [https://docs.h2o.ai/h2o/latest-stable/h2o-docs/automl.html](https://docs.h2o.ai/h2o/latest-stable/h2o-docs/automl.html) (tendrías que instalar Java)

Está genial Alfredo! 

![image](https://user-images.githubusercontent.com/54676992/109484279-8c1c4e80-7a80-11eb-9775-570fe9053fd0.png)
