### ISSUE TITLE
[W7-Kaggle_competition] Ana G.

### ISSUE THREAD

**Issue by AnaAGG** [Ironhack-Data-Madrid-Enero-2021/W7-Kaggle_competition#2]
https://github.com/AnaAGG/P5_Diamonds.git

**Comment by olmocorell** [comment]
¡¡Hola Maifren!! 
¿Pensabas que había terminado de corregir? pues no.
Te cuento... tu readme está perfecto, no tengo nada que decir.
El Jupyer de data cleaning está perfecto también
Luego, por otra parte, me habría molado ver cómo hacías un pipeline con muchos más modelos del tirón, te entrenabas muchos y elegías los mejores. Después de eso, habría molado ver cómo haces grid search cv para tunear los hiperparámetros y elegir cuáles son los parámetros que se ajustan a tu modelo más, en función de los datos.

Y por último, te pongo un pequeño resumen de info útil sobre este proyecto.
Te dejo un poco de info sobre el proyecto a modo de resumen ¿vale?
Para esto proyecto hay que elegir el modelo que mejor te prediga en base a unos datos. Para elegir el mejor modelo de machine learning, hay cuatro variables que podemos controlar con unos determinados datos:

- Limpieza de los datos
- Cómo separamos los datos para hacer el train/test.
- Qué modelo utilizamos.
- Qué parámetros utilizamos en ese modelo.

Para cada uno de ellos hay una estrategia:

1. **Encoders & Standarization**: para las variables categóricas: [aquí](https://medium.com/@michaeldelsole/what-is-one-hot-encoding-and-how-to-do-it-f0ae272f1179) (también hay otras estrategias, como [esta](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html), o incluso hacer un diccionario donde a cada letra le asignes un valor numérico relativo al resto. Y esto es positivo cuando tenemos datos que, además, mejoran en calidad, es decir, que si tenemos 7 clasificaciones, pero además, van de peor a mejor, igual es conveniente que el algoritmo tenga en cuenta esa variable numérica.
2. **Cross-validation:** para garantizar el corte de los datos: [aquí](https://medium.com/analytics-vidhya/introduction-to-cross-validation-k-fold-7ed9cbd0ed7b)
3. Modelo de regresión/categorización: probar varios 🤷🏻‍♂️, [aquí](https://mahiprashanth866.medium.com/top-10-best-machine-learning-algorithms-acd9fd2c0471) y [aquí](https://medium.com/technology-nineleaps/popular-machine-learning-algorithms-a574e3835ebb)
4. **Grid search**: para las permutaciones de los parámetros: [aquí](https://medium.com/fintechexplained/what-is-grid-search-c01fe886ef0a)

Y podemos hacer directamente Grid Search CV que une los puntos 2 y 4 😄 

¡¡Seguimoooooooooooooooos!! ¡¡¡Esto se acaba!!!!

![U4SezaC](https://user-images.githubusercontent.com/57899051/110699928-a926ef00-81ef-11eb-9be4-b584cfa0399b.png)
