### ISSUE TITLE
[W7-Kaggle_competition] Mario García

### ISSUE THREAD

**Issue by MarioGar25** [Ironhack-Data-Madrid-Enero-2021/W7-Kaggle_competition#7]
My repo: https://github.com/MarioGar25/Diamonds-everywhere

**Comment by breogann** [comment]
Hola Mario! 🙋🏻‍♂️

########################################################################

En **general**, los objetivos y estrategias del proyecto:

Hay que elegir el modelo que mejor te prediga en base a unos datos. Para elegir el mejor modelo de machine learning, hay cuatro variables que podemos controlar:

- Procesamiento de los datos
- Cómo separamos los datos para hacer el train/test.
- Qué modelo utilizamos.
- Qué parámetros utilizamos en ese modelo.

Para cada uno de ellos hay una estrategia:

1. **Encoders & Standarization**: para las variables categóricas: [aquí](https://medium.com/@michaeldelsole/what-is-one-hot-encoding-and-how-to-do-it-f0ae272f1179) (también hay otras estrategias, como é[sta](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html), o incluso hacer un diccionario donde a cada letra le asignes un valor numérico relativo al resto. Claro que esto te puede valer cuando tienes pocos datos.
2. ***Cross-validation:** para garantizar el corte de los datos: [aquí](https://medium.com/analytics-vidhya/introduction-to-cross-validation-k-fold-7ed9cbd0ed7b)
3. **Modelo de regresión**: probar varios, [aquí](https://medium.com/technology-nineleaps/popular-machine-learning-algorithms-a574e3835ebb)
4. **Grid search**: para las permutaciones de los parámetros: [aquí](https://medium.com/fintechexplained/what-is-grid-search-c01fe886ef0a)

**o grid search con cross-validation, como has hecho*

########################################################################

En **particular**: 

- Respecto a la **organización del repositorio y el readme:**
    - Para este proyecto no hacía falta modularizar y hacer un archivo de utils en src. Pero que lo hayas hecho igualmente está genial. Por rizar un poco más el rizo, podrías hacer dos funciones para la limpieza y entonces pasársela al csv de test directamente.
    - En cuanto a contenido, está bien pero puedes meter más info. Incluye la estructura de los datos y su significado; deja claro que has investigado sobre el dominio de los datos.
- El **código 👩‍💻:**
    - Los jupyters están muy bien explicados: con títulos y comentarios 👏
    - Se te ha impreso un warning infinito. Puedes:

        ```python
        import warnings
        warnings.filterwarnings('ignore')
        ```

    - Súper top el pipeline de la regresión lineal de sklearn
    - Súper top también el gridsearchCV. Entiendo que te ha dado error porque estabas re-ejecutándolo y lo has parado manualmente, ¿no?
    - Como bonus personal, ¿para qué sirve cada parámetro?, ¿por qué utilizando un valor u otro mejora o no el resultado?
    - El pipeline también lo puedes construir "manualmente" para probar varios modelos a la vez.
    - Guarda los modelos! Se pueden guardar con pickle: [https://machinelearningmastery.com/save-load-machine-learning-models-python-scikit-learn/](https://machinelearningmastery.com/save-load-machine-learning-models-python-scikit-learn/). Ahora habrá tardado "poco" en entrenar, pero créeme que te interesa guardar el modelo entrenado para poder importarlo y pasárselo a nuevos datos en el futuro.
    - Por último, explora H20:  [https://docs.h2o.ai/h2o/latest-stable/h2o-docs/automl.html](https://docs.h2o.ai/h2o/latest-stable/h2o-docs/automl.html) (tendrás que instalar Java)

Has procesado los datos, entrenado dos modelos, hecho gridsearchCV y has hecho submissions; que era el objetivo.

A darle duro al proyecto final 💪  🚀

![image](https://user-images.githubusercontent.com/54676992/109484279-8c1c4e80-7a80-11eb-9775-570fe9053fd0.png)
