### ISSUE TITLE
[W7-Kaggle_competition] Jean Charles Yamada

### ISSUE THREAD

**Issue by yamadajc** [Ironhack-Data-Madrid-Enero-2021/W7-Kaggle_competition#8]
https://github.com/yamadajc/Diamonds_kaggle_competition

**Comment by breogann** [comment]
Hola Jeancha! 🙋🏻‍♂️

En **general**, los objetivos y estrategias del proyecto:

Hay que elegir el modelo que mejor te prediga en base a unos datos. Para elegir el mejor modelo de machine learning, hay cuatro variables que podemos controlar:

- Procesamiento de los datos
- Cómo separamos los datos para hacer el train/test.
- Qué modelo utilizamos.
- Qué parámetros utilizamos en ese modelo.

Para cada uno de ellos hay una estrategia:

1. **Encoders & Standarization**: para las variables categóricas: [aquí](https://medium.com/@michaeldelsole/what-is-one-hot-encoding-and-how-to-do-it-f0ae272f1179) (también hay otras estrategias, como é[sta](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html), o incluso hacer un diccionario donde a cada letra le asignes un valor numérico relativo al resto. Claro que esto te puede valer cuando tienes pocos datos.
2. ***Cross-validation:** para garantizar el corte de los datos: [aquí](https://medium.com/analytics-vidhya/introduction-to-cross-validation-k-fold-7ed9cbd0ed7b)
3. **Modelo de regresión**: probar varios, [aquí](https://medium.com/technology-nineleaps/popular-machine-learning-algorithms-a574e3835ebb)
4. **Grid search**: para las permutaciones de los parámetros: [aquí](https://medium.com/fintechexplained/what-is-grid-search-c01fe886ef0a)

**o grid search con cross-validation, como has hecho*

########################################################################

En **particular**: 

- Respecto a la **organización del repositorio y el readme:**
    - En cuanto a contenido, está bien pero puedes meter más info. Incluye la estructura de los datos y su significado. También el enlace a la competición.
    - No te olvides de que tus proyectos constituirán tu portfolio. Asegúrate de revisar el texto de los jupyters y del readme para quitar erratas y revisar la ortografía.
- El **código 👩‍💻:**
    - Los jupyters están muy bien explicados.
    - En la función de mapeo:

        ```python
        def mapeo (df):
            print ('Cut:', set (df ['cut'])) 
            print ('Color:', set (df ['color'])) 
            print ('Clarity:', set (df ['clarity']))
            df["cut"] = df["cut"].map({'Ideal':1,'Good':2,'Very Good':3,'Fair':4,'Premium':5})
            df["color"] = df["color"].map({'E':1,'D':2,'F':3,'G':4,'H':5,'I':6,'J':7})
            df["clarity"] = df["clarity"].map({'VVS1':1,'IF':2,'VVS2':3,'VS1':4,'I1':5,'VS2':6,'SI1':7,'SI2':8})                     
            return df
        ```

        el concepto de mapeo está genial. Los print, si es una función que vas a utilizar una vez, los quitaría. Aunque entiendo que lo haces a modo de comprobación. En vez de prints, puedes poner un raiseError si la longitud de los sets es mayor que 1. Aprovecha e implementa el error handling.

    - Como bonus personal, ¿para qué sirve cada parámetro?, ¿por qué utilizando un valor u otro mejora o no el resultado? Has puesto cuatro, estos son los parámetros que recibe Random Forest regressor: [https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html)
    - Por lo demás, el entrenamiento de los datos es un código sencillo; como tiene que ser. Pero has entrenado sólo un modelo. El objetivo no era sólo encontrar una buena predicción, sino utilizar varias estrategias para conseguirlo. Haz un pipeline para hacer el mismo proceso que has hecho pero utilizando varios modelos a la vez. Tienes la estructura para encontrar los parámetros, ahora sólo tienes que iterar por varios modelos.
    - Por último, explora H20:  [https://docs.h2o.ai/h2o/latest-stable/h2o-docs/automl.html](https://docs.h2o.ai/h2o/latest-stable/h2o-docs/automl.html) (tendrás que instalar Java)

Has procesado los datos, entrenado un modelo, hecho gridsearchCV y has hecho submissions; que era el objetivo. Pero puedes entrenar más modelos haciendo un pipeline. Es algo que tendrás que hacer para el proyecto final si quieres predecir valores o categorías.

A darle duro al proyecto final 💪  🚀

![image](https://user-images.githubusercontent.com/54676992/109484279-8c1c4e80-7a80-11eb-9775-570fe9053fd0.png)

**Comment by breogann** [comment]
Ya te lo dije en los anteriores, no has creado un `.gitignore` 🔪

**EDITO**: Guarda el modelo. https://machinelearningmastery.com/save-load-machine-learning-models-python-scikit-learn/. Ahora habrá tardado "poco" en entrenar, pero créeme que te interesa guardar el modelo entrenado para poder importarlo y pasárselo a nuevos datos en el futuro.
